apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-ingress

  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

spec:
  ingressClassName: nginx

  rules:
    - http:

        paths:

          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # Authentication
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3001

          # Streaming
          - path: /api/streaming
            pathType: Prefix
            backend:
              service:
                name: streaming
                port:
                  number: 3002

          # Admin
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3003

          # Chat / WebSocket
          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 3004