replicaCount:
  auth: 1
  streaming: 3
  admin: 1
  chat: 1
  frontend: 1
  mongo: 1

images:
  auth:
    repository: streamingapp-auth
    tag: latest
    pullPolicy: IfNotPresent

  streaming:
    repository: streamingapp-streaming
    tag: latest
    pullPolicy: IfNotPresent

  admin:
    repository: streamingapp-admin
    tag: latest
    pullPolicy: IfNotPresent

  chat:
    repository: streamingapp-chat
    tag: latest
    pullPolicy: IfNotPresent

  frontend:
    repository: streamingapp-frontend
    tag: latest
    pullPolicy: IfNotPresent

  mongo:
    repository: mongo
    tag: "6"
    pullPolicy: IfNotPresent

service:
  auth:
    port: 3001

  streaming:
    port: 3002

  admin:
    port: 3003

  chat:
    port: 3004

  frontend:
    port: 80

  mongo:
    port: 27017

config:
  mongoUri: mongodb://mongo:27017/streamingapp
  clientUrls: http://localhost:31142

secret:
  jwtSecret: changeme

ingress:
  enabled: true
  className: nginx
  host: ""
